#!/bin/csh -f
#+
# KCWI library of scripts
#
# NAME
#     kcwiStop - stop all kcwi software
#
# SYNOPSIS
#       kcwiStop
#
# DESCRIPTION
#       This script will shutdown the KCWI gui interfaces.
#       This includes the kcwi control desktop, slitmask
#       control desktop, tkrose, and the autodisplay software.
#
# ARGUMENTS
#
# OPTIONS
#
# EXAMPLES
#
# ENVIRONMENT VARIABLES
#
# FILES
#
# SERVERS & KEYWORDS
#
# SCRIPTS CALLED
#
# EXIT STATUS
#     0 - normal exit, no error
#     1 - script aborted by an interrupt
#
# Modification History:
#       2012-apr-1      MK      Original version
#       2012-oct-31     MK      Added stop audio alerts
#	2012-Dec-07	GDW	Added tklogger
#	2012-Dec-08	GDW	Added xterm
#	2013-Jan-12	GDW	Add eventsounds, remove audio alerts
#       2013-Oct-14     MK      Added piglet stop
#       2014-Apr-2      MK      Added mxy_logging stop
#       2014-Dec-13     MK      Moved stop autodisplay earlier and 
#                                  added a delay.
#       2016-Jul-14     LR      Adapted for KCWI
#------------------------------------------------------------------------------

# ---------------------------------------------------------------
# Stop the KCWI DS9 Display utilities
# ---------------------------------------------------------------
echo "Stopping Autodisplay for Blue Camera. Pausing 2 sec"
kcwi stop kcwidisplayb
sleepdots 2

echo "Stopping Autodisplay for focal plane camera. Pausing 2 sec"
kcwi stop kfcdisplay
sleepdots 2

echo "Stopping Autodisplay for Magiq Guider. Pausing 2 sec"
kcwi stop magiqdisplay
sleepdots 2

echo "Stopping Configuration Manager Backend. Pausing 2 sec"
kcwi stop kcwiConfManager
sleepdots 2

echo "Stopping Eventsounds. Pausing 2 sec"
kcwi stop eventsounds
sleepdots 2

echo "Stopping SoundBoard. Pausing 2 sec"
kcwi stop soundboard
sleepdots 2

echo "Stopping Exposure GUI."
kcwi stop kcwiExposureGui
echo "Stopping Status GUI."
kcwi stop kcwiStatusGui
echo "Stopping Calibration GUI."
kcwi stop kcwiCalibrationGui
echo "Stopping Offset GUI."
kcwi stop kcwiOffsetGui






# ---------------------------------------------------------------
# Stop the KCWI Desktop
# ---------------------------------------------------------------
kcwi stop kdesktop 
kcwi stop kdesktop_eng
kcwi stop kdesktop_oa

# ---------------------------------------------------------------
# Stop the compase rose
# ---------------------------------------------------------------
#stop_tkrose 

# ---------------------------------------------------------------
# Stop the CSU audio alerts
# ---------------------------------------------------------------
#stop_audioalerts

# ---------------------------------------------------------------
# halt eventsounds
# ---------------------------------------------------------------
#eventsounds -k

# ---------------------------------------------------------------
# halt the piglet
# ---------------------------------------------------------------
#/net/kalahuipuaa/local/apps1/kroot/summit/instr/koa/piglet -k

# ---------------------------------------------------------------
# halt tklogger,.,
# ---------------------------------------------------------------
#kcwiStopTklogger

# ---------------------------------------------------------------
# halt xterm,.,
# ---------------------------------------------------------------
#kcwiStopXterm

# ---------------------------------------------------------------
# check that rpcinfo table is cleared of clients
# ---------------------------------------------------------------

#set rpccount = `checkrpc`
#if ( $rpccount != 0 ) then
#  # kill the clients
#  kcwiKillAllClients
#  # wait a few seconds
#  sleepdots 5
#  # clean the rpc table
#  checkrpc -kill
#else
# print completion message....
cat <<EOF

      ----------------------------------------------------------
		KCWI software shutdown complete
      ----------------------------------------------------------
EOF
endif
sleepdots 5
exit
